Development:

stripe_secret_key: 'sk_test_51MeX5zSHsSITW5Noh3gUfh6QMLIVDVi3gxeROZdCnPORfd4YuVWexwBHd6jUDhSYT1RmMSAPJh0dXT1t5XpV74sd00MaEyRext'

stripe_publishable_key: 'pk_test_51MeX5zSHsSITW5Novj4iJpd0JgHHGiwF1nTKHlIBSZpBheKgESChBRmCnhYcVI3D6GLf4EFVz9bOumCsprIcZ5nA00PpbpQA3I'

